config/routes.rb
Rails.application.routes.draw do
  
  root 'about#index'

  devise_for :users
    
  get 'about' => 'about#index'
  get 'books/booklist' => 'books#booklist'
  get 'books/booklist_all' => 'books#booklist_all'
  get 'books/new_books' => 'books#new_books'
  get 'statistics' => 'statistics#index'
  get 'technologies' => 'technologies#index'
  get 'loans' => 'loans#index'
  resources :books do
    resources :reviews
  end
  
  resources :categories
  resources :authors
  resources :libraries
  resources :media
  resources :authors
  resources :countries
  resources :readers
  resources :tags
  
  resources :statistics, only:[] do
    collection do
      get 'authors_by_country'
    end
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/library.rb
# == Schema Information
#
# Table name: libraries
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string
#  description :text
#

class Library < ApplicationRecord
	has_many :books
	has_many :loans, dependent: :destroy
	
	mount_uploader :image, ImageUploader

	extend FriendlyId
    friendly_id :name, use: :slugged
    
	def to_s
		name
	end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :find_library, only: [:show, :edit, :update, :destroy]
  
  def index
    @page_title = 'Libraries'
    @libraries = Library.all.order("name ASC")
  end

  def new
    @page_title = 'Add library'
    @library = Library.new
  end

  def create
    @library = Library.new(library_params)
    if @library.save
      flash[:info] = "Library Created"
      redirect_to libraries_path
    else
      render 'new'
    end
  end

  def show
    @books = @library.books
    @page_title = @library.name
  end

  def edit
  end

  def update
    @library.update(library_params)
    flash[:info] = "Library updated"
    redirect_to libraries_path
  end

  def destroy
    @library.destroy
    flash[:danger] = "Library removed"
    redirect_to libraries_path
  end

  private
  def library_params
    params.require(:library).permit(:name, :image, :description, :details, :notes)
  end

  def find_library
    @library = Library.friendly.find(params[:id])
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for @library, html: {multipart: true}  do  |f| %>

<%= render 'shared/error_messages', object: f.object %>
 
<div class="form-group row">
<%= f.label :name, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.text_field :name, class: 'form-control' %><br />
</div>
</div>

<div class="form-group row">
<%= f.label :image, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.file_field :image, class: 'form-control' %><br />
</div>
</div>

<div class="form-group row">
<%= f.label :details, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.text_area :details, class: 'form-control' %>
</div>
</div>

<div class="form-group row">
<%= f.label :description, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.text_area :description, class: 'form-control' %>
</div>
</div>

<div class="form-group row">
<%= f.label :notes, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.text_area :notes, class: 'form-control' %>
</div>
</div>


<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>

<% end %>

app/views/libraries/create.html.erb
<h1>Libraries#create</h1>
<p>Find me in app/views/libraries/create.html.erb</p>

app/views/libraries/destroy.html.erb
<h1>Libraries#destroy</h1>
<p>Find me in app/views/libraries/destroy.html.erb</p>

app/views/libraries/edit.html.erb
	<h2>Edit library</h2>
	<%= render 'form' %>

app/views/libraries/index.html.erb
<h2 class="inline-form">Libraries <span class="badge badge-info"><%= @libraries.count %></span></h2>

<a class="btn btn-primary btn-lg inline-form float-right" href="/libraries/new" role="button">New</a>

<table class="table table-striped">
	<tr>
		<th>Library</th>
		<th>Books</th>
		<th>Image</th>
		<th>Actions</th>
	</tr>
	<% @libraries.each do |library| %>
		<tr>
			<td><%= library.name %></td>
			<td><%= library.books.count %></td>
			<td><%= image_tag library.image_url(:thumb).to_s %></td>
			<td><%= link_to "Show", library_path(library) %> | <%= link_to "Edit", edit_library_path(library) %> | <%= link_to "Delete", library_path(library), method: :delete, data: {confirm: 'Are you sure'} %> </td>

		</tr>
	<% end %>
</table>

app/views/libraries/new.html.erb
	<h2>Add a new library</h2>
	<%= render 'form' %>

app/views/libraries/show.html.erb
<div class="row">
		<div class="col-md-4">
			<%= image_tag @library.image_url.to_s, class: "img-fluid"   %>
		</div>

		<div class="col-md-8">
			<div class="book-info">
				
				<h5 class="section-title-home">
					<div class="section-title-home-content">
						<i class="mdi mdi-library"></i>
				<%= @library.name %>
			</div></h5>
			

			<div id="tabs">
			<ul>
				<li><a href="#tabs-1">Details</a></li>
				<li><a href="#tabs-2">Description</a></li>
				<li><a href="#tabs-3">Notes</a></li>
			</ul>
		    <div id="tabs-1">
				<ul>
					<li><%= pluralize(@library.books.count, "book") %></li>
					
				</ul>
				<div><%= markdown(@library.details) %></div>	
				<div class="links btn-group">
					<%= link_to "Back", libraries_path, class: "btn btn-custom" %>

					<%= link_to "Edit", edit_library_path, class: "btn btn-custom" %>
					<%= link_to "Delete", library_path(@library), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-custom" %>

				</div>
			</div>
		    <div id="tabs-2">
				<div class="book-description">
					<%= markdown(@library.description) %>
				</div>
			
			</div>
			<div id="tabs-3">
				<div class="book-description">
					<%= markdown(@library.notes) %>
					
					
				</div>
			</div>
		
	    </div>	



				
				
					
				</div>
				
				
			</div>
		</div>
	</div>

	<script>
		$( function() {
			$( "#tabs" ).tabs();
		} );
</script>

app/views/libraries/update.html.erb
<h1>Libraries#update</h1>
<p>Find me in app/views/libraries/update.html.erb</p>