config/routes.rb
Rails.application.routes.draw do
  
  root 'about#index'

  devise_for :users
    
  get 'about' => 'about#index'
  get 'books/booklist' => 'books#booklist'
  get 'books/booklist_all' => 'books#booklist_all'
  get 'books/new_books' => 'books#new_books'
  get 'statistics' => 'statistics#index'
  get 'technologies' => 'technologies#index'
  get 'loans' => 'loans#index'
  resources :books do
    resources :reviews
  end
  
  resources :categories
  resources :authors
  resources :libraries
  resources :media
  resources :authors
  resources :countries
  resources :readers
  resources :tags
  
  resources :statistics, only:[] do
    collection do
      get 'authors_by_country'
    end
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#  image       :string
#

class Tag < ApplicationRecord
	has_many :taggings
	has_many :books, through: :taggings

	scope :tops, -> {where(name: "top")}
	scope :news, -> {where(name: "new")}
	
	mount_uploader :image, ImageUploader

	def to_s
		name
	end

	def self.counts
      self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
    end
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
before_action :find_tag, only: [:show, :edit, :update, :destroy]
 
  def index
    @page_title = 'Tags'
    @tags = Tag.all.order("name ASC")

  end

  def new
    @page_title = 'Add tag'
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:info] = "Tag created"
      redirect_to tags_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @tag.update(tag_params)
    
      flash[:info] = "Tag updated"
    
      redirect_to tags_path
  
  end

  def show
    @tags = Tag.all
    @books = @tag.books
  end

  def destroy
    @tag.destroy
    flash[:danger] = "Tag removed"
    redirect_to tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :image, :description)
  end

  def find_tag
    @tag = Tag.find(params[:id])
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @tag, html: {multipart: true} do |f| %>

<%= render 'shared/error_messages', object: f.object %>
 
<div class="form-group row">
<%= f.label :name, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.text_field :name, class: 'form-control' %><br />
</div>
</div>

<div class="form-group row">
<%= f.label :image, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.file_field :image, class: 'form-control' %><br />
</div>
</div>

<div class="form-group row">
<%= f.label :description, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.text_area :description, class: 'form-control' %>
</div>
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', tags_path, class: 'btn btn-default' %>

<% end %>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<h2>Edit tag</h2>

<%= render 'form' %>

app/views/tags/index.html.erb
<h2 class="inline-form">Tags <span class="badge badge-info"><%= @tags.count %></span></h2>

<a class="btn btn-primary btn-lg inline-form float-right" href="/tags/new" role="button">New</a>
<br/>
<table class="table table-striped">
	<tr>
		<th>Tag</th>
		<th>Books</th>
		<th>Image</th>
		<th>Actions</th>
	</tr>
	<% @tags.each do |tag| %>
		<tr>
			<td><%= tag.name %></td>
			<td><%= tag.books.count %></td>
			<td><%= image_tag tag.image_url(:thumb).to_s %></td>
			<td><%= link_to "Show", tag_path(tag.id) %> | <%= link_to "Edit", edit_tag_path(tag.id) %> | <%= link_to "Delete", tag_path(tag), method: :delete, data: {confirm: 'Are you sure'} %> </td>

		</tr>
	<% end %>
</table>

app/views/tags/new.html.erb
<h2>Add new tag</h2>

<%= render 'form' %>

app/views/tags/show.html.erb
<div class="row">
		<div class="col-md-4">
			<%= image_tag @tag.image_url.to_s, class: "img-fluid" %>
		</div>

		<div class="col-md-8">
			<div class="book-info">
				
				<h5 class="section-title-home">
					<div class="section-title-home-content">
						<i class="mdi mdi-tag"></i>
				<%= @tag.name %>
			</div></h5>

				<h6><%= pluralize(@tag.books.count, "book") %></h6>
				<div class="book-description"><%= markdown(@tag.description)
				 %></div>
				
				<div class="links btn-group">
					<%= link_to "Back", tags_path, class: "btn btn-custom" %>

					<%= link_to "Edit", edit_tag_path, class: "btn btn-custom" %>
					<%= link_to "Delete", tag_path(@tag), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-custom" %>

				</div>
			</div>
		</div>
	</div>

<%= render 'books/book_large' %>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>