config/routes.rb
Rails.application.routes.draw do
  
  root 'about#index'

  devise_for :users
    
  get 'about' => 'about#index'
  get 'books/booklist' => 'books#booklist'
  get 'books/booklist_all' => 'books#booklist_all'
  get 'books/new_books' => 'books#new_books'
  get 'statistics' => 'statistics#index'
  get 'technologies' => 'technologies#index'
  get 'loans' => 'loans#index'
  resources :books do
    resources :reviews
  end
  
  resources :categories
  resources :authors
  resources :libraries
  resources :media
  resources :authors
  resources :countries
  resources :readers
  resources :tags
  
  resources :statistics, only:[] do
    collection do
      get 'authors_by_country'
    end
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan < ApplicationRecord
	
	belongs_to :library
	belongs_to :reader
	belongs_to :book
	
	scope :sorted, -> {order(date_end: :asc)}	
	scope :sorted_desc, -> {order(date_end: :desc)}
	scope :available, -> {where(is_returned: false)}

	self.per_page = 24
	
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController

	def index
  	@loans = Loan.available.page(params[:page]).sorted
    @return_date_min = Loan.available.minimum(:date_end)
    @page_title = 'Loans'

  	if params[:library]
      @library_id = Library.find_by(name: params[:library]).id
      @loans = Loan.available.where(library_id: @library_id).page(params[:page]).sorted
      @return_date_min = Loan.available.where(library_id: @library_id).minimum(:date_end)

    elsif params[:reader]
      @reader_id = Reader.find_by(name: params[:reader]).id
      @loans = Loan.available.where(reader_id: @reader_id).page(params[:page])
      @return_date_min = Loan.available.where(reader_id: @reader_id).minimum(:date_end)
    end 
  	
 
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_loan.html.erb
<div class="row">
		<% @loans.each do |loan| %>
		

		<div class="col-md-3 col-xl-2 col-sm-6">
			<div class="card-deck">
				<div class="card">
					<a href="/books/<%= loan.book_id %>">		
						<%= image_tag loan.book.try(:image_url).to_s, class: "img-fluid card-img-top" %>
						<div class="bg-light">
						<%= image_tag loan.reader.try(:image_url).to_s , class: "avatar-small" %>
						
					<ul class="list-inline list-unstyled">
					    <% loan.book.try(:tags).try(:each) do |tag| %>
					    <li class="list-inline-item badge badge-info text-center"> <%= tag.name %></li>
					    <% end %>
					    </ul>
														
						
						</div>
						</a>
						<div class="card-text">
						<p class="card-text text-center flex-item"grow"><%= loan.book.try(:title) %></p>
						</div>
					
				<div class="card-footer text-center">
      <small class="text-muted"><%= remove_unwanted_words time_ago_in_words(loan.created_at) %> ago</small>
    </div>
				</div>
			</div>
		</div>
		<% end %>
	
	</div>

app/views/loans/index.html.erb
<% if params[:library] %>
	  <h3><%= params[:library] %> <span class="badge badge-info"><%= @loans.count %></span>
	
	<%= render 'books/date' %>


	<%= link_to "Back", loans_path, class: "btn btn-outline-secondary btn-sm float-right small-device"  %>
	</h3>
	
	<% elsif params[:reader] %>
	  <h3><%= params[:reader] %> <span class="badge badge-info"><%= @loans.count %></span>
	  	<%= render 'books/date' %>
		  <%= link_to "Back", loans_path, class: "btn btn-outline-secondary btn-sm float-right small-device"  %>
	</h3>

	<% else %>

<div class="header-books">	
	  <h3 class="header-selection">Loans <span class="badge badge-info"><%= @loans.count %> </span>

		<%= render 'books/date' %>

	  </h3>	

	 

	 <div class="header-selection">

		<% Library.all.each do |library| %>
		<% if library.loans.count > 0 %>
		<%= link_to library.name, loans_path(library: library.name), class: "btn btn-outline-secondary btn-sm", style: "margin-left: 5px;" %>
		<% end %>
		<% end %>

		<% Reader.all.each do |reader| %>
		<% if reader.loans.count > 0 %>
		<%= link_to reader.name, loans_path(reader: reader.name), class: "btn btn-outline-info btn-sm", style: "margin-left: 5px;" %>
		<% end %>
		<% end %>

				
	</div>
</div>
<% end %>

<% if @loans.count == 0 %>
	<h4>There are currently no books lent</h4>
	<% else %>	
	  <%= form_tag(books_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Book" %>
      <%= submit_tag "Search", :name => nil %>
      <% end %>
      <br>
  
	<%= render 'loan' %>
	<% end %>
	
	<%= will_paginate @books, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
	
	<%= link_to "Add Book", new_book_path, class: 'btn btn-outline-secondary btn-sm' %>