config/routes.rb
Rails.application.routes.draw do
  
  root 'about#index'

  devise_for :users
    
  get 'about' => 'about#index'
  get 'books/booklist' => 'books#booklist'
  get 'books/booklist_all' => 'books#booklist_all'
  get 'books/new_books' => 'books#new_books'
  get 'statistics' => 'statistics#index'
  get 'technologies' => 'technologies#index'
  get 'loans' => 'loans#index'
  resources :books do
    resources :reviews
  end
  
  resources :categories
  resources :authors
  resources :libraries
  resources :media
  resources :authors
  resources :countries
  resources :readers
  resources :tags
  
  resources :statistics, only:[] do
    collection do
      get 'authors_by_country'
    end
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
	has_many :books

	mount_uploader :image, ImageUploader
	
	extend FriendlyId
    friendly_id :name, use: :slugged

	def to_s
		name
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def index
    @page_title = 'Categories'
    @categories = Category.all.order("name ASC")
  end

  def new
    @page_title = 'Add category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:info] = "Category Created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @categories = Category.all
    @books = @category.books
    
    
  end

  def edit
  end

  def update
     @category.update(category_params)
     flash[:info] = "Category updated"
     redirect_to categories_path
  end

  def destroy
    @category.destroy
    flash[:danger] = "Category removed"
    redirect_to categories_path
  end

  
  private 
  def category_params
    params.require(:category).permit(:name, :image, :description)
  end

  def find_category
  @category = Category.friendly.find(params[:id])
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

<%= render 'shared/error_messages', object: f.object %>
 
<div class="form-group row">
<%= f.label :name, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.text_field :name, class: 'form-control' %><br />
</div>
</div>

<div class="form-group row">
<%= f.label :image, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.file_field :image, class: 'form-control' %><br />
</div>
</div>

<div class="form-group row">
<%= f.label :description, class: "col-sm-2 col-form-label" %>
<div class="col-sm-10">
<%= f.text_area :description, class: 'form-control' %>
</div>
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>

<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
	
<h2>Edit category</h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<h2 class="inline-form">Categories <span class="badge badge-info"><%= @categories.count %></span></h2>

<a class="btn btn-primary btn-lg inline-form float-right" href="/categories/new" role="button">New</a>
<br/>
<table class="table table-striped">
	<tr>
		<th>Category</th>
		<th>Books</th>
		<th>Image</th>
		<th>Actions</th>
	</tr>
	<% @categories.each do |category| %>
		<tr>
			<td><%= category.name %></td>
			<td><%= category.books.count %></td>
			<td><%= image_tag category.image_url(:thumb).to_s %></td>
			<td> <%= link_to "Show", category_path(category.id) %> |
				 <%= link_to "Edit", edit_category_path(category) %> | 
				 <%= link_to "Delete", category_path(category), method: :delete, data: {confirm: 'Are you sure'} %> </td>

		</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
	
<h2>Add new category</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="row">
		<div class="col-md-4">
			<%= image_tag @category.image_url.to_s, class: "img-fluid" %>
		</div>

		<div class="col-md-8">
			<div class="book-info">
				
				<h5 class="section-title-home">
					<div class="section-title-home-content">
						<i class="mdi mdi-tag"></i>
				<%= @category.name %>
			</div></h5>

				<h6><%= pluralize(@category.books.count, "book") %></h6>
				<div class="book-description"><%= markdown(@category.description)
				 %></div>
				
				<div class="links btn-group">
					<%= link_to "Back", categories_path, class: "btn btn-custom" %>

					<%= link_to "Edit", edit_category_path, class: "btn btn-custom" %>
					<%= link_to "Delete", category_path(@category), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-custom" %>

				</div>
			</div>
		</div>
	</div>

<%= render 'books/book_large' %>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>